---
db:
  engine: mysql
  username: admin
  password: '123456'
  host: 192.168.1.52
  port: 3306
  charset: utf8mb4
  database: user_growth
  showSQL: 'true'
  maxIdleConns: 2
  maxOpenConns: 10
  connMaxLifetime: 30
